Avoid modifying Dockerfile for nvidia driver installation
esa-prl/rover_docker pull request #15
Opened 2020-08-26 18:07 UTC by wieset

Instead of modifying the Dockerfile, the nvidia driver package to be installed is now passed as an argument to the Dockerfile.

In addition, I removed the manual gazebo installation to handle it through rosdep to be in line with our ROS2 installation instructions. I also combined multiple small RUN commands into one to reduce the number of layers.

2020-08-26 18:17 UTC, wieset commented
Closes https://github.com/esa-prl/rover_docker/issues/12

2020-08-27 08:50 UTC, maxehrhardt requested changes

2020-08-27 08:50 UTC, maxehrhardt commented on README.md
> +
I would move that down to the chapter "Usage"

2020-08-27 09:54 UTC, wieset commented on README.md
> +
I put it there since you need to use the command when you want to setup the container the first time. But I'm also fine with moving it, will do!

2020-09-07 15:46 UTC, wieset commented
@maxehrhardt Can we merge this? :)

2020-09-10 07:44 UTC, maxehrhardt approved these changes

2020-09-10 07:45 UTC, merged